### ISSUE TITLE
How to make the ball move? I have followed the demo-video....

### ISSUE THREAD

**Issue by AK51** [ahmadsayed/node-red-contrib-web-babylonjs#14]
Hi,

I followed the video and try to move the ball, but it does not move...
I have tried in Ubuntu and in Window 10
Would you have time to take a look? Thx

Btw, for Ubuntu, the node-red crash sometimes
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration...
my node-red was fine until I install this 3D package....

[{"id":"2b6c49cd.b09f96","type":"tab","label":"Flow 8","disabled":false,"info":""},{"id":"3cb84de09df6da63","type":"sphere","z":"2b6c49cd.b09f96","scene":"94f3825768329669","material":"0b367347b72269fc","name_conf_a":"ball","segments_conf_n":32,"diameter_conf_n":1,"diameterX_conf_n":"","diameterY_conf_n":"","diameterZ_conf_n":"","arc_conf_n":1,"slice_conf_n":1,"updatable_conf_b":true,"sideOrientation_conf_a":"2","pos_x":0,"pos_y":0,"pos_z":0,"scale_x":1,"scale_y":1,"scale_z":1,"rot_x":0,"rot_y":0,"rot_z":0,"x":880,"y":540,"wires":[[]]},{"id":"0f9d6568cdee8a56","type":"inject","z":"2b6c49cd.b09f96","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"x\":0,\"y\":0,\"z\":0}","payloadType":"json","x":660,"y":520,"wires":[["3cb84de09df6da63","d0ea9d591a702b2a"]]},{"id":"782c528feb8a488e","type":"box","z":"2b6c49cd.b09f96","scene":"94f3825768329669","material":"98b40a243a132d76","name_conf_a":"pizzabox","size_conf_n":1,"height_conf_n":"","width_conf_n":"","depth_conf_n":"","updatable_conf_b":false,"sideOrientation_conf_a":"2","pos_x":0,"pos_y":"-0.5","pos_z":0,"scale_x":1,"scale_y":"0.1","scale_z":1,"rot_x":0,"rot_y":0,"rot_z":0,"x":910,"y":600,"wires":[[]]},{"id":"3253616cb20b6421","type":"inject","z":"2b6c49cd.b09f96","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"x\":0,\"y\":1,\"z\":0}","payloadType":"json","x":660,"y":600,"wires":[["3cb84de09df6da63"]]},{"id":"d0ea9d591a702b2a","type":"debug","z":"2b6c49cd.b09f96","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":880,"y":500,"wires":[]},{"id":"94f3825768329669","type":"scene","name":"default","overlay":false},{"id":"0b367347b72269fc","type":"material","name":"default","diffuse":"#d11a1a","specular":"#c72929","alpha":"0.5"},{"id":"98b40a243a132d76","type":"material","name":"blue","diffuse":"#232fd7","specular":"#211ee6","alpha":"0.5"}]

**Comment by ahmadsayed** [comment]
Hi @AK51, sometimes this issue happens when having the multiple browsers opened or multiple scenes in the the same flow, there is already opened an issue on I will give it more attention, 

as a workaround close the browser that points to /scene till you clear the flow, or delete the flow.json file.

to make the ball move, in the sample I have I updated the coordinates by using inject with repeat and update the coordinate using function node.

**Comment by ahmadsayed** [comment]
https://github.com/ahmadsayed/node-red-contrib-web-babylonjs/commit/9c45d3a6740a2d820fd47114d10830d10c7ce269

**Comment by AK51** [comment]
I have reinstalled the node-red to the newest version and tried your 
https://github.com/ahmadsayed/node-red-contrib-web-babylonjs/tree/master/samples
I have one browser opened and only your flow, but once I opened the scene, node-red crashed....

**Comment by ahmadsayed** [comment]
@AK51 Interesting I am not able to re-generate it, would you please give me the full logs you see.

**Comment by ahmadsayed** [comment]
@AK51  you are building from the source, or you pull it from node pallete, as just pushed the update yesterday it still in node-red manage pallet show version 0.0.13 not 0.0.15
